spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/siuuu?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  jpa:
    generate-ddl: 'false'
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto:
    open-in-view: false

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: 'email'
    password: 'password'
    port: '587'

  redis:
    host: 127.0.0.1
    port: '6379'

  main.allow-bean-definition-overriding: true